### ISSUE TITLE
Wrong unfocused text-field color in dark-mode

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#162]
I just switched to Java 13 so I'm now using Java 11 version of JMetro instead of Java 8 version.

I noticed that in Dark Mode, the text color is stuck at "black" even when the focus is moved to another text color:

![image](https://user-images.githubusercontent.com/3038088/84350101-bc386000-ab86-11ea-820c-1dcbf4c5aa72.png)

It should look like this:

![image](https://user-images.githubusercontent.com/3038088/84350041-9ad77400-ab86-11ea-9ad9-8606c5ab1324.png)

After a few trial and error I noticed that removing the following two css styles will fix the problem:

```
#eqContainerPanel {
    -fx-padding: 0 5 0 5;
}
.spacing {
    -fx-spacing: 5px;
}
```

Is this a bug?

**Comment by runiter** [comment]
Any updates on this one? This one is kind of a showstopper

**Comment by dukke** [comment]
Hi Saeid,

I'm going to try to see if I have time to look at this issue by the end of the week. Could you just check if this also happens in Java 11?

Thanks

**Comment by runiter** [comment]
Yes, I just tested and same problem happens in Java 11.

**Comment by dukke** [comment]
Hey @runiter , just to let you know that I'll be working on this issue starting end of this week. Not totally sure if I'll have time this week but will definitely have time for it next week.

**Comment by runiter** [comment]
Awesome, thank you

**Comment by runiter** [comment]
Any luck?

**Comment by dukke** [comment]
Sorry Saeid but I've still been busy lately. I'm counting on starting to look at JMetro issues next week or perhaps starting this Sunday/Saturday.

**Comment by dukke** [comment]
If in the meantime you find anything new about this issue by debugging please add the info here, would be greatly appreciated. Thanks!

**Comment by runiter** [comment]
Sure, I will share if I find anything.

**Comment by dukke** [comment]
Hey @runiter 

I've tested this and seems to be working. Perhaps you're using an older version?
![image](https://user-images.githubusercontent.com/2707487/89076265-d832d380-d377-11ea-82cd-107e270c0ab7.png)

Latest JMetro Java 11 compatible version is "11.6.13"

**Comment by dukke** [comment]
It may have been fixed meanwhile as well because I think I remember a time where I spotted this problem.

**Comment by dukke** [comment]
@runiter I'm closing this issue as like I said in a comment a few days ago, it appears to be fixed.

If you have any issues with this issue and would like to add more comments feel free to re-open and comment.

**Comment by dukke** [comment]
Hi @runiter,

Sorry I thought you were using maven dependencies. I've now copied the jars and javadoc to the release in github. You can download from there now.

Thanks

**Comment by saeidN** [comment]
Hi @dukke 
Unfortunately the problem I reported in this ticket still persists even with the latest version of your library.

But I noticed that that's impossible for me to create a short code sample that reproduces this issue.
It seems to happen in my application only!

To help with debugging, can you tell me how I can force the text-field color to be a certain color in css?
I noticed that jmetro keeps setting text fillColor to black as soon as mouse is hovered away from text-field.
What's the easiest way of setting the color text fillColor to say blue regardless of whether or not it is focused?

**Comment by saeidN** [comment]
Hi @dukke
Unfortunately the problem I reported in this ticket still persists even with the latest version of your library.

But I noticed that that's impossible for me to create a short code sample that reproduces this issue.
It seems to happen in my application only!

To help with debugging, can you tell me how I can force the text-field color to be a certain color in css?
I noticed that jmetro keeps setting text fillColor to black as soon as mouse is hovered away from text-field.
What's the easiest way of setting the color text fillColor to say blue regardless of whether or not it is focused?

**Comment by dukke** [comment]
Hi @runiter 

I'm reopening this issue then but I'll need more information as I'm not able to reproduce it and I'd ask you to test this under java11 (which won't probably make a difference but who knows..).

Please attach an example, simple test app that shows the problem happening.

Thx

**Comment by runiter** [comment]
I did test it in Java 11 and same issue. But it works in Java 8.

I cannot create a simple test app for this issue because in simple app it works fine!!!
Only in my complex app this problem occurs!

I like to debug the problem in my local machine but I'm not sure how to track it.

Using SceneView I noticed that fillColor of TextField > Shape keeps changing to black when it should be white.
Do you know how to control the fillColor of that particular component using css?

I tried this but it didn't work:

```
.text-input {
    -fx-text-fill: black;
}
```

**Comment by dukke** [comment]
Ideally you should write a rule with a greater level of specificity than JMetro, just to make sure JMetro doesn't win over your rule (google CSS specificity).
BTW, this is written in the JMetro documentation, you should consult it. Ideally you should do it before asking here.

As such it might work to do something like this (haven't tried it but think it'll work):
```
TextField {
    -fx-text-fill: red;
}
```
(this will work if TextField has a higher specificity than .text-input, which I think it does)

Alternatively add more styleclasses/IDs/etc to your rule...

**Comment by dukke** [comment]
This seems to be the same bug as issue #171

**Comment by dukke** [comment]
I'm going to close down this issue. I'll comment on the other issue which this one is a duplicate of just so discussions don't get dispersed between 2 separate issues about the same problem.

Thx!
